imbrn/v8n

.circleci/config.yml
.eslintrc.json
package.json
yarn.lock

* Add lint test to CircleCI tasks;
* Add pre-commit linting;
* Add ESLint with Prettier linting config.

Add support for linting code

---

src/v8n.js

Fix bugs prones implementation details:
* Fix proxies calls chain;
* Separate `modifiers` related stuff into an object;

Improve core implementation

---

src/v8n.js

* Remove unused code and unecessary duplications;

Improve implementation details

---

.eslintrc.json
package.json
src/v8n.js
src/v8n.test.js
yarn.lock

* Now to declare custom rules, the used must call the `v8n.extend` method
instead of declaring manual rules.

Update custom rules definition API

---

src/v8n.js

These modifications improve the code readability and provides a better
scenario for documentation and API exposure.

Add constructors to Rule and ValidationException

---

package.json
rollup.config.js
yarn.lock

* Add files configuration in package.json;
* Set rollup build configurations;
* Add npm script for publishing.

Prepare project for publishing

---

package.json

* Change main entry to use 'cjs' file;
* Add 'module' entry with 'esm' file.

Fix package.json file

---

package.json
rollup.config.js
yarn.lock

* Add keys for `jsdelivr` and `unpkg`;
* Add source maps to distributed files;
* Clean dist folder before build.

Fix distribution files

---

.github/CONTRIBUTING.md
.gitignore

Concerning #38 this adds a small yet useful CONTRIBUTING file with some basic information. Improvements welcome!

Add CONTRIBUTING guidelines

---

README.md
src/v8n.js
src/v8n.test.js

Add async validation support

---

src/Modifier.js
src/Rule.js
src/ValidationException.js
src/v8n.js
src/v8n.test.js

Refactor core functionalities

---

package.json
rollup.config.js
src/Rule.js
src/v8n.js
yarn.lock

Fix build process for distribution files

Fix build process for distribution files

---

package.json

* Fix wrong devDependency that was marked as dependency

Fix package.json dependencies

---

CHANGELOG.md
package.json

Prepare project for releasing v1.2.0
🎉🎉

Prepare version 1.2.0

---

README.md

Fix a wrong example in the README file. The example that was being used was not correct and the result was different from the one we actually get when execute the code.

Fix wrong example in README

---

CHANGELOG.md

Update CHANGELOG entries to include the "fix bad example" change.

Add 'Fix bad example' in CHANGELOG changes

---

.circleci/config.yml

Trying to fix github pages auto deploy with CircleCI. (I hope it works now!)

Add circleci fingerprints

---

src/v8n.js

This change is a refactoring to improve code readability: some of the rule functions' auxiliaries were removed and replaced by inline tests.
> Note: It increases the final bundle size a little but not in a significant way. It still remains around 2.2KB gzipped.
It's related to issue #91

Improve code readability

---

docs/api/README.md

Swaps uppercase() examples for vowel() ones.

fix(docs): sets correct example for vowel()

---

CHANGELOG.md
src/Rule.js
src/v8n.js
src/v8n.test.js

Fix every schema bug

---

docs/Validation.md
docs/api/README.md

Some fixes to the documentation.

Some documentation fixes

---

CHANGELOG.md
package.json

Preparation for releasing version `v1.3.0`

Prepare for version v1.3.0

---

CHANGELOG.md
package.json

Prepare for the new release of version `v1.3.2`

Version v1.3.2

---

CHANGELOG.md
package.json

Version 1.3.3

---

.github/workflows/push.yml

Add Github Actions push and pull request jobs for testing the application

GH Action for push and pull requests

---

CHANGELOG.md
package.json

Preparing for releasing version v1.5.0.

Prepare for release 1.5.0

---

CHANGELOG.md
src/v8n.js

Inefficient regular expression complexity of lowercase() and uppercase() regex could lead to a denial of service attack.

fix inefficient regular expressions on lowercase and uppercase rules

---

CHANGELOG.md
package.json

Preparing for releasing version v1.5.1.

Prepare for release 1.5.1
