src/v8n.js, src/v8n.test.js
The `equal` rule tests if the validated value is exact the same
as the passed expected value. It uses the triple equal operator (===).
=> Add `equal` rule

src/v8n.js
Regarding issue #41 this makes ValidationException essentially an instance of Error including a stack trace as any regular error would have. This provides some consistency across JavaScript.
As of now I'm implementing this without ES6, though an ES6 approach would be nicer. This project already transpiles with Babel but seems to not use any new features like classes.
This introduces no changes in API whatsoever.
=> Make ValidationException inherit from Error

rollup.config.js
Transpile from es6 to es5 when building distribution files.
It fixes #44
=> Fix bug with distribution files

README.md, src/v8n.js, src/v8n.test.js
Related to issue #24.
This will add the ability to receive information about every failed rule in the validation instead of failing fast once any error happens.
```javascript
v8n()
.number()
.between(5, 10)
.testAll(true); // [Rule { name: 'number', ... }, Rule  { name: 'between', ... }]
v8n()
.number()
.between(5, 10)
.testAll(7); // []
```
The implementation is fairly straightforward.
=> Add ability to return all errors from validation as array

README.md, src/v8n.js, src/v8n.test.js
It also changes the ValidationException API (no breaking changes) for better traversing errors through the `cause` and `target` properties. It allows us to perform a much better report when using validation composition.
=> Add rule `schema`

src/Context.js, src/Modifier.js, src/v8n.js, src/v8n.test.js
The immutable approach is a good thing for code clarity, functional style and a lot of other improvements. But the most important benefit of  this change it to make validation objects able to be `forked` into another validation objects, like this:
```javascript
const a = v8n().number();
const b = a.min(40);
```
This kind of behavior was not possible in the previous mutable implementation as the `b.min(40)` call was also changing the `a` strategy.
In the new immutable approach, now `a` and `b` are different in their behaviors:
```javascript
a.test(40); // true
b.test(40); // false
```
=> Refactor validation object to make it immutable

src/Context.js, src/v8n.test.js
Make it to return an array of ValidationException objects for each
failed rule, instead of just returning these rules.
Note: a ValidationException object contains a reference to the rule
which caused the fail.
=> Change `testAll` function

src/v8n.test.js
* Remove executable code from "describe" body:
This change makes easy to debug tests by allowing single tests to be
performed without seeing output logs from random places.
=> Improve tests definitions

CHANGELOG.md, docs/api/README.md, src/v8n.js, src/v8n.test.js
This is a preliminary implementation and should be validated yet.
We have to make some decisions like what we should expect when no validation is given. Should we get a valid or invalid result?
In the current implementation, I decided to make the arguments spread to an array `(... validations)` instead of getting an array directly. What do you think about?
And this PR closes #53.
=> Add "any" rule for branching validations

CHANGELOG.md, docs/Validation.md, docs/api/README.md, src/v8n.js, src/v8n.test.js
This allows for optional validation as described in #94.
=> Add a rule for optional validation

CHANGELOG.md, README.md, docs/Validation.md, docs/api/README.md, src/Context.js, src/ValidationError.js
This change was made due proposed by #104.
This change does not require a major version update as the `ValidationException` object was not exposed as a public API in the current version 1. But as the documentation exposes the naming `ValidationException`, this maybe should be in a patch update.
- This is an internal naming change, but it affects documentation.
=> Rename ValidationException to ValidationError

.github/CONTRIBUTING.md
Small update to the CONTRIBUTING guide to reflect library changes, specifically the fact that `v8n.js` no longer contains all the code.
Fixes #109
=> Update contributing guide to reflect library changes

CHANGELOG.md, src/v8n.js
Make the `integer` rule logic to fallback to an integer test polyfill when `Number.isInteger` is not available.
Fixes #117
=> Fix bug with `integer` rule

CHANGELOG.md, src/v8n.js, src/v8n.test.js
This PR fixes a bug related by #119 where `Infinity` values were being wrongly tested with _range-based_ rules.
=> Fix bug with `Infinity` values in range based rules

CHANGELOG.md, docs/api/README.md, src/v8n.js, src/v8n.test.js
This rule validates that a number has some sort of numeric value. The implementation is the same as jQuery's `isNumeric`. Notably `Infinity` and `NaN` are **not** numeric. The test suite is basically the same as the one in the [jQuery docs](http://api.jquery.com/jquery.isnumeric/).
Fixes #139
=> Add numeric rule for testing numeric strings

CHANGELOG.md, docs/api/README.md, src/v8n.js, src/v8n.test.js
Add support for considering trimmed empty strings valid by the `optional` rule, as requested by #140 
It depends on a flag (the second parameter) to be set to true. It defaults to false, so the current behavior is still working the same. But now with that flag set to `true`, trimmed empty strings will be considered valid by the `optional` rule:
```js
v8n().optional(v8n().number(), true).test("") == true
v8n().optional(v8n().number(), true).test("  ") == true
```
The current behavior still working as before:
```js
v8n().optional(v8n().number()).test("") == false
v8n().optional(v8n().number()).test("  ") == false
```
=> Consider trimmed empty strings valid by optional rule

CHANGELOG.md, src/v8n.js, src/v8n.test.js
The optional rule didn't work when an empty was passed because the conditional was not considering the real `validation` when the value was an empty string, as reported by #149 
This fix inverts the conditional and checks if the `considerEmptyString` flag is enabled, so it skips to the real validation when it's false.
=> Fix optional rule bug

src/v8n.js, src/v8n.test.js
Another fix to optional rule. Now it guarantees that it's going to work with the `string` rule.
=> Fix optional rule

src/Rule.js, src/v8n.js, src/v8n.test.js
Async rules nested within a schema were not tested async. A `testAsync()` test would pass before an async rule was resolved. See #161 
I fixed that by applying the same pattern as modifiers with `.simple` and `.async` to schema's.
=> fix: async rule with schema

CHANGELOG.md, docs/api/README.md, src/v8n.js
Added `proxylessContext` to allow v8n to work in ES5 environments without the `Proxy` object. This is mostly the work of @NoemiRozpara, but with the included bug fix from @ev-akarel (my other account), from the original PR #171 that was abandoned.
Fixes #45 
- This would require changing the way v8n tests are run, since it needs to be sandboxed in an ES5 environment. I believe this can/should be done, but perhaps not within the scope of this PR.
=> Proxyless context

.github/workflows/npm-publish.yml
Use yarn for publishing to npm using GH Action.
This PR also changes the `node-version` matrix syntax to keep consistency with all Github Action configurations.
=> Use yarn for publishing to npm using GH Action

.github/workflows/npm-publish.yml
Adds a Github Action workflow trigger that permits manually deploy dispatching (npm publish).
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
=> Manually deploy dispatching for GH Actions

CHANGELOG.md, package.json
Bumps the version in the package.json for the release. To be fair, this should have been done in a previous pull request - but the automatic release to npm was not implemented when that PR was made. This *should* be the last necessary step to publish 1.4.0.
=> Bump npm package version for release 1.4.0

.github/workflows/npm-publish.yml
The automatic documentation publish action was using windows path separators (`\`) which are likely not supported in the relevant GitHub action. The path to the documentation was not being found and publishing errored.  The path separators were switched for unix style forward slashes.
Fixes #221
=> Use correct path to vuepress dist

CHANGELOG.md, src/v8n.js
The check to verify that the `Proxy` object existed in the given environment would always return `true`. Fixed the `typeof` comparison. This was totally my fault. ☹️
=> Fixed faulty Proxy check
